KWD-48-md-succes
KateShepel/ice-cream pull request #14
Opened 2022-11-25 12:27 UTC by AndrewPechnikov

2022-11-25 14:34 UTC, alex-shepel requested changes

2022-11-25 14:34 UTC, alex-shepel commented on src/components/footer/index.html
> +		© 2019 - IceCream.<br>
Краще не вставляти символи типу © напряму. А використовувати юнікод. Для цього символу `&#xa9;`.

2022-11-27 10:26 UTC, alex-shepel approved these changes

2022-11-27 10:30 UTC, KateShepel approved these changes

2022-11-27 11:05 UTC, merged