Feature/kwd 68 products section style
KateShepel/ice-cream pull request #15
Opened 2022-11-25 14:17 UTC by AndrewPechnikov

2022-11-25 14:40 UTC, alex-shepel requested changes

2022-11-27 10:27 UTC, alex-shepel approved these changes

2022-11-27 10:37 UTC, KateShepel requested changes

2022-11-27 10:37 UTC, KateShepel commented on src/utils/sign-section.scss
> +	font-family: "Titan One";
Може зробимо змінні для шрифтів? Наприклад `font-primary` та `font-secondary`?

2022-11-27 11:01 UTC, AndrewPechnikov commented on src/utils/sign-section.scss
> +	font-family: "Titan One";
Давай, з'явиться світло, я додам їх у змінні.

2022-11-28 10:12 UTC, KateShepel approved these changes

2022-11-28 10:29 UTC, merged