Feature/kwd 67 reviews mobile style
KateShepel/ice-cream pull request #19
Opened 2022-11-28 16:31 UTC by AndrewPechnikov

Я написав стилі і одразу додав слайдер.

2022-11-30 19:15 UTC, KateShepel approved these changes

2022-12-02 13:30 UTC, alex-shepel requested changes

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.js
> +let swiper = new Swiper('.mySwiper', {
тут по ідеї можна просто
```
new Swiper('.mySwiper', {
  pagination: {
    el: '.swiper-pagination',
    clickable: true,
  },
});
```
без `let swiper = `

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.scss
> +	-webkit-justify-content: center;
Ці властивості не треба прописувати, їх parcel сам проставить, якщо треба буде. Це для сумісності з усіма браузерами.
```
-webkit-box-pack: center;
-ms-flex-pack: center;
-webkit-justify-content: center;
```
```
-webkit-box-align: center;
-ms-flex-align: center;
-webkit-align-items: center;
```
Тобі достатньо прописати `justify-content: center;` та `align-items: center;`.

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.scss
> +	background: #fff;
Має бути змінна `$light-background` чи якась така)

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.scss
> +		font-family: "DM Sans";
має бути змінна ддя шрифта `DM Sans`

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.scss
> +			background-image: url(/src/img/lines__reviews.png);
краще вказути відносний шлях, котрий починається `./` тобто ось так `url("./src/img/lines__reviews.png")`

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.scss
> +			background-image: url(/src/img/quotes.png);
краще вказути відносний шлях, котрий починається `./` тобто ось так `url("./src/img/quotes.png")`

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.scss
> +		color: #000000;
Використай змінну для кольору будь ласка

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.scss
> +	color: #000;
Використай змінну для кольору будь ласка

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.html
> +          <img src="/src/img/reviews__avatar.jpg" width="85px" alt="" class="reviews__avatar" />
краще вказути відносний шлях, котрий починається `./` тобто ось так `src="./src/img/reviews__avatar.jpg"`

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.html
> +          <img src="/src/img/reviews__avatar.jpg" width="85px" alt="" class="reviews__avatar" />
краще вказути відносний шлях, котрий починається `./` тобто ось так `src="./src/img/reviews__avatar.jpg"`

2022-12-02 13:30 UTC, alex-shepel commented on src/components/reviews/index.html
> +          <img src="/src/img/reviews__avatar.jpg" width="85px" alt="" class="reviews__avatar" />
краще вказути відносний шлях, котрий починається `./` тобто ось так `src="./src/img/reviews__avatar.jpg"`

2022-12-02 13:30 UTC, alex-shepel commented on src/index.html
> +    <script src="/src/components/reviews/index.js"></script>
краще вказути відносний шлях, котрий починається `./` тобто ось так `src="./src/components/reviews/index.js"`

2022-12-02 19:18 UTC, KateShepel approved these changes

2022-12-02 19:25 UTC, alex-shepel approved these changes

2022-12-02 20:58 UTC, merged