add feature/kwd47 html mobile
KateShepel/ice-cream pull request #2
Opened 2022-11-15 14:38 UTC by KateShepel

2022-11-15 14:46 UTC, alex-shepel requested changes

2022-11-15 14:46 UTC, alex-shepel commented on src/components/contacts/index.html
> +    <li>
Перевір роботу пріттіера. Виглядає, ніби він не спрацював.

2022-11-15 14:46 UTC, alex-shepel commented on src/components/contacts/index.html
> +<ul>
Треба закрити тег.

2022-11-15 14:46 UTC, alex-shepel commented on src/components/hero/index.html
> +  <!-- Прописать якоря для навигации по странице -->
Додай до коментаря префікс `TODO:`

2022-11-15 15:00 UTC, alex-shepel approved these changes

2022-11-21 15:10 UTC, alex-shepel approved these changes

2022-11-23 11:05 UTC, AndrewPechnikov approved these changes
Я продивився. Все класно.

2022-11-24 11:01 UTC, merged