Feature/kwd 66 galery mobile style
KateShepel/ice-cream pull request #20
Opened 2022-11-30 14:05 UTC by AndrewPechnikov

2022-11-30 19:17 UTC, KateShepel approved these changes

2022-12-02 19:21 UTC, KateShepel approved these changes

2022-12-02 19:57 UTC, alex-shepel requested changes

2022-12-02 19:57 UTC, alex-shepel commented on src/components/gallery/index.scss
> +		// transform-style: preserve-3d;
Закоментований код, ай-яй-яй))

2022-12-02 19:57 UTC, alex-shepel commented on src/components/gallery/index.html
> +  <div class="container galery__container">
Давай зробимо через `<ul>` та `<li>`, адже це список елементів)

2022-12-05 09:46 UTC, KateShepel approved these changes

2022-12-05 19:36 UTC, alex-shepel approved these changes

2022-12-05 19:37 UTC, merged