KWD-71: Додає оформлення header mobile
KateShepel/ice-cream pull request #21
Opened 2022-11-30 19:10 UTC by KateShepel

2022-12-01 11:49 UTC, AndrewPechnikov requested changes

2022-12-01 11:49 UTC, AndrewPechnikov commented on src/components/navigation/index.scss
> +.logo {
Треба зробити невеликий відступ від верху. Також у reset, постав margin 0 для body.

2022-12-01 11:49 UTC, AndrewPechnikov commented on src/components/navigation/index.scss
> +.button__menu {
Кидається в очі трошки не відцентрована по вертикалі іконка menu, Її звісно ідеально ставити не треба, бо у макеті вона не відцентрована, але мені здається треба зробити її трохи нижче.

2022-12-01 11:49 UTC, AndrewPechnikov commented on src/components/navigation/index.html
> +      <img src="/src/img/ice-cream-logo.png" width="50" alt="company logo" class="logo__icon" />
Вставити лого яке я скинув.

2022-12-02 20:08 UTC, KateShepel commented on src/components/navigation/index.html
> +      <img src="/src/img/ice-cream-logo.png" width="50" alt="company logo" class="logo__icon" />
![image](https://user-images.githubusercontent.com/108049103/205377117-d838055a-6392-49f7-a279-98e425adcd5d.png)

2022-12-02 20:09 UTC, KateShepel commented on src/components/navigation/index.html
> +      <img src="/src/img/ice-cream-logo.png" width="50" alt="company logo" class="logo__icon" />
![image](https://user-images.githubusercontent.com/108049103/205377230-6cf908ba-91cf-407f-b1e7-45fdcde74656.png)

2022-12-02 20:14 UTC, alex-shepel requested changes

2022-12-02 20:14 UTC, alex-shepel commented on src/components/navigation/index.html
> +      <svg width="20" height="12" aria-label="Перемикач мобільного меню">
Переклади англійською будь ласка)

2022-12-02 20:14 UTC, alex-shepel approved these changes

2022-12-05 19:38 UTC, AndrewPechnikov approved these changes

2022-12-06 08:39 UTC, merged