KWD-88-fix-decore-content-succes
KateShepel/ice-cream pull request #23
Opened 2022-12-01 09:23 UTC by AndrewPechnikov

2022-12-02 19:23 UTC, KateShepel approved these changes

2022-12-02 20:18 UTC, alex-shepel requested changes

2022-12-02 20:18 UTC, alex-shepel commented on src/components/products/index.html
>          <img src="/src/img/products-1.png" alt="" class="product-card__img" />
Зроби шлях відносним через `./`, будь ласка

2022-12-02 20:18 UTC, alex-shepel commented on src/components/products/index.html
> +            <use href="/src/img/svg/symbol-defs.svg#icon-arrow-right"></use>
І тут

2022-12-02 20:18 UTC, alex-shepel commented on src/components/products/index.html
>          <img src="/src/img/products-2.png" alt="" class="product-card__img" />
І тут

2022-12-02 20:18 UTC, alex-shepel commented on src/components/products/index.html
> +            <use href="/src/img/svg/symbol-defs.svg#icon-arrow-right"></use>
І тут

2022-12-02 20:18 UTC, alex-shepel commented on src/components/products/index.html
>          <img src="/src/img/products-3.png" alt="" class="product-card__img" />
І тут

2022-12-02 20:18 UTC, alex-shepel commented on src/components/products/index.html
> +            <use href="/src/img/svg/symbol-defs.svg#icon-arrow-right"></use>
І тут

2022-12-02 20:18 UTC, alex-shepel commented on src/components/products/index.scss
> +		// border-radius: 50%;
Закоментований код, ай-яй-яй)

2022-12-05 09:48 UTC, KateShepel approved these changes

2022-12-05 19:40 UTC, merged