KWD-74: Додає стилі секції Традицій
KateShepel/ice-cream pull request #25
Opened 2022-12-05 14:34 UTC by KateShepel

2022-12-05 19:43 UTC, alex-shepel approved these changes

2022-12-06 20:54 UTC, AndrewPechnikov requested changes

2022-12-07 09:41 UTC, KateShepel commented on src/components/tradition/index.html
> +    <p class="tradition__subtitle">tradition and love</p>
![image](https://user-images.githubusercontent.com/108049103/206143531-7abc7bea-cd42-4bb6-ae14-119453f632d2.png)
Шрифти самі підтягнуться, коли змержимо попередній ПР, вони унаслідуються від `body` та `h`.

2022-12-07 09:42 UTC, KateShepel commented on src/components/tradition/index.html
> +      Curabitur lacinia enim at ex blandit, vel pellentesque adio elementum. Mauris rhoncus orci in
Теж саме.

2022-12-07 09:44 UTC, KateShepel commented on src/index.scss
> +@import './components/navigation/index.scss';
Ти дивився чи є в тебе той файл??? У мене в цій гілці файл `components/navigation/index.scss` є і помилки немає.

2022-12-07 09:47 UTC, AndrewPechnikov commented on src/index.scss
> +@import './components/navigation/index.scss';
Ти зробила merge, і помилка зникла.

2022-12-07 10:14 UTC, AndrewPechnikov approved these changes

2022-12-07 16:37 UTC, merged