Feature/kwd-72 add hero styles
KateShepel/ice-cream pull request #26
Opened 2022-12-05 14:35 UTC by KateShepel

2022-12-05 19:44 UTC, alex-shepel approved these changes

2022-12-05 19:44 UTC, alex-shepel approved these changes

2022-12-06 20:54 UTC, AndrewPechnikov requested changes

2022-12-07 09:20 UTC, KateShepel commented on src/components/hero/index.html
>  <section id="home" class="hero">
Якщо поставити марджин, тоді не має можливості фарбувати бекграунд. Можливо краще тобі додати верхній паддінг?

2022-12-07 09:24 UTC, KateShepel commented on src/components/hero/index.html
>  <section id="home" class="hero">
![image](https://user-images.githubusercontent.com/108049103/206139590-7259223d-bbc2-475d-9e6b-35b6156502b8.png)
Я, наприклад, використовую паддінги у своїх секціях, щоб була змога пофарбувати бекграунд.

2022-12-07 09:28 UTC, KateShepel commented on src/components/hero/index.html
>  <section id="home" class="hero">
![image](https://user-images.githubusercontent.com/108049103/206140628-3d11f570-eada-4af8-8d1b-eb147755aeeb.png)
Щоб не було ось такого порожнього розриву.

2022-12-07 09:41 UTC, AndrewPechnikov commented on src/components/hero/index.html
>  <section id="home" class="hero">
Тобто ти хочеш щоб усі секції були впритул. Добре, тоді перероблю у себе, бо я не правильно зроби.

2022-12-07 09:45 UTC, AndrewPechnikov approved these changes

2022-12-07 09:45 UTC, merged