Feature/kwd 73 menu mobile scss
KateShepel/ice-cream pull request #27
Opened 2022-12-07 16:59 UTC by KateShepel

2022-12-08 07:22 UTC, alex-shepel requested changes

2022-12-08 07:22 UTC, alex-shepel commented on src/components/navigation/index.html
> +      aria-expanded="true"
тут все ж `false` має бути, адже за замовчуванням меню закрите

2022-12-09 07:44 UTC, AndrewPechnikov approved these changes

2022-12-09 18:23 UTC, alex-shepel approved these changes

2022-12-09 18:26 UTC, merged