KWD-83: styles hero tablet
KateShepel/ice-cream pull request #37
Opened 2022-12-12 09:35 UTC by KateShepel

2022-12-12 12:39 UTC, AndrewPechnikov requested changes

2022-12-12 12:39 UTC, AndrewPechnikov commented on src/components/header/index.scss
> +      url('./img/tablet/hero-bg-picture.png'), url('./img/tablet/hero-pink-circle.png');
У тебе фонові картинки виходять за контейнер.
![image](https://user-images.githubusercontent.com/73440973/207047311-6ac4afd2-66b8-4a50-ab81-5f3701f48a6d.png)

2022-12-13 06:36 UTC, AndrewPechnikov requested changes

2022-12-13 06:36 UTC, AndrewPechnikov commented on src/components/header/index.scss
> +    background-image: url('./img/hero-icecream.png'), url('./img/hero-circle.svg');
Можливо не обрізати коло для бекграунду мобілки
![image](https://user-images.githubusercontent.com/73440973/207244110-3d3a3858-deb2-4472-9947-b6bd47fe36e1.png)

2022-12-13 11:48 UTC, alex-shepel approved these changes

2022-12-14 07:39 UTC, AndrewPechnikov approved these changes

2022-12-14 09:12 UTC, merged