Feature/kwd 88 products tablet style
KateShepel/ice-cream pull request #41
Opened 2022-12-12 19:19 UTC by AndrewPechnikov

2022-12-12 20:22 UTC, KateShepel approved these changes

2022-12-13 12:10 UTC, alex-shepel requested changes

2022-12-13 12:10 UTC, alex-shepel commented on src/index.scss
> +@import "./components/product-card/index.scss";
давай перенесемо `product-card` до папки `blocks`, адже в `components` у нас частини сторінки з розміткою HTML

2022-12-14 10:17 UTC, alex-shepel approved these changes

2022-12-14 11:28 UTC, merged