KWD-100: Додає стилі секції навігації для ПК
KateShepel/ice-cream pull request #50
Opened 2022-12-15 10:08 UTC by KateShepel

2022-12-15 15:11 UTC, alex-shepel approved these changes

2022-12-16 16:22 UTC, AndrewPechnikov requested changes

2022-12-16 16:22 UTC, AndrewPechnikov commented on src/components/navigation/index.scss
> +      color: $main-color;
Може анімацію додаш на ховер?

2022-12-18 09:13 UTC, AndrewPechnikov approved these changes

2022-12-18 17:05 UTC, merged