KWD-103-стили продуктов для ПК
KateShepel/ice-cream pull request #53
Opened 2022-12-15 11:58 UTC by AndrewPechnikov

2022-12-15 15:26 UTC, alex-shepel requested changes

2022-12-15 15:26 UTC, alex-shepel commented on src/components/products/index.html
> +        <picture c>
Тут здається артефакт `c` :)

2022-12-15 15:26 UTC, alex-shepel commented on src/blocks/product-card.scss
> +	padding: 161px 16px 41px 16px;
Можна скоротити `padding: 161px 16px 41px`, якщо захочеш)

2022-12-15 15:26 UTC, alex-shepel commented on src/blocks/product-card.scss
> +		padding: 152px 11px 40px 11px;
Можна скоротити `padding: 152px 11px 40px`, якщо захочеш)

2022-12-15 15:26 UTC, alex-shepel commented on src/blocks/product-card.scss
> +		padding: 163px 45px 50px 45px;
Можна скоротити `padding: 163px 45px 50px`, якщо захочеш)

2022-12-15 15:26 UTC, alex-shepel commented on src/components/products/index.html
> +          <source media="(min-width: 375px)" srcset="./img/products-1.png" />
А чому `min-width: 375px`, якщо розмір мобілки `320px`, а планшету `768px`?

2022-12-15 15:26 UTC, alex-shepel commented on src/components/products/index.html
> +          <img src="./img/products-2.png" alt="Icecream" class="product-card__img" />
Перенеси будь ласка зображення таблетки до папки `img/tablet`.

2022-12-15 15:35 UTC, KateShepel approved these changes

2022-12-15 19:54 UTC, AndrewPechnikov commented on src/components/products/index.html
> +          <img src="./img/products-2.png" alt="Icecream" class="product-card__img" />
У мене для таблетки і для телефону одна і та ж картинка.

2022-12-19 09:34 UTC, alex-shepel approved these changes

2022-12-19 09:39 UTC, merged