KWD-62: Додає скидання базових стилів
KateShepel/ice-cream pull request #6
Opened 2022-11-22 10:19 UTC by KateShepel

2022-11-23 11:43 UTC, AndrewPechnikov requested changes

2022-11-23 11:43 UTC, AndrewPechnikov commented on src/utils/reset.scss
>    box-sizing: border-box;
Можливо потрібно додати псевдрелементи ::after та ::before

2022-11-24 11:41 UTC, AndrewPechnikov approved these changes

2022-11-24 12:26 UTC, alex-shepel approved these changes

2022-11-24 14:02 UTC, merged