kwd 99 spread img
KateShepel/ice-cream pull request #64
Opened 2022-12-19 13:00 UTC by AndrewPechnikov

2022-12-22 09:30 UTC, KateShepel requested changes

2022-12-22 09:30 UTC, KateShepel commented on src/components/header/index.scss
> +  background-image: url("./img/common/hero-icecream.png"), url("./img/svg/bg-pink-circle.svg");
Мабуть морозиво має бути в папці `mobile`, так як я його завантажувала і для інших розмірів екрану.

2022-12-23 06:02 UTC, alex-shepel approved these changes

2022-12-29 15:35 UTC, KateShepel approved these changes

2022-12-29 19:56 UTC, merged