KWD-116 fix horisontal line
KateShepel/ice-cream pull request #71
Opened 2022-12-30 19:56 UTC by AndrewPechnikov

2022-12-30 20:21 UTC, alex-shepel requested changes

2022-12-30 20:21 UTC, alex-shepel commented on src/components/footer/index.scss
> +		width: 99vw;
![image](https://user-images.githubusercontent.com/79785130/210109163-db05dbea-f3d6-4b8d-a16d-5477137976fd.png)

2022-12-30 20:22 UTC, alex-shepel commented on src/components/footer/index.scss
> +		width: 99vw;
На деяких розмірах все одно з'являється скрол

2023-01-01 16:00 UTC, KateShepel approved these changes

2023-01-01 16:01 UTC, alex-shepel approved these changes

2023-01-01 16:01 UTC, merged